### ISSUE TITLE
Time for Simulation Creation Increases with Python Requirements

### ISSUE THREAD

**Issue by kfrey-idm** [InstituteforDiseaseModeling/idmtools#1395]
# Description

The time to create simulations on COMPS increases with the size of python requirements.

# What I Did

As an example, I ran two experiments, each with 500 simulations. The simulations used PythonTask, and the python script itself was minimal with no package dependencies.

In experiment 1, I asked for 'pyshp==2.0.1' as part of the assets. (Unused package; selected as example small requirement)
In experiment 2, I asked for 'emod_api==1.2.2' as part of the assets. (Unused package; selected as example large requirement)

Experiment 1 created ~55 sims/sec
Experiment 2 created  ~4 sims/sec

**Comment by ZDu-IDM** [comment]
Done with idmtools release 1.7.5
