### ISSUE TITLE
Change log filename format for rollover logs

### ISSUE THREAD

**Issue by jps1** [InstituteforDiseaseModeling/idmtools#1663]
Currently rollover logs are named "idmtools.log.#".  However, ".1" etc are not known filename extensions, so if I download that file or try to view it within COMPS, nothing knows how to handle that kind of file.  If the filename format could be changed to something like "idmtools.#.log" instead, that would maintain the same basic functionality but allow those files to be better handled by other tools.

**Comment by devclinton** [comment]
@shchen-idmod @emilydriano @ZDu-IDM , does anyone know if I can close this now? I *think* we fixed it, but I am not sure

**Comment by shchen-idmod** [comment]
This is fixed.

**Comment by devclinton** [comment]
Yeah, it appears so by https://github.com/InstituteforDiseaseModeling/idmtools/blob/75a4b9021f86cbe77f93a98bd3843647ae660d8f/idmtools_core/idmtools/core/logging.py#L317-L319
