### ISSUE TITLE
AnalyzerManager working_dir bug

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#1665]
If Analyzer does not define any working_dir 
class MyAnalyzer(IAnalyzer)
    def __init__(self):
        super().__init__()
when we call analyzermanager, we can pass working_dir as parameter.
but following code, does not pick up working_dir from analyzermanager. instead of still using empty working_dir

https://github.com/InstituteforDiseaseModeling/idmtools/blob/240f8095a494fa4f2cccf235fb82b92d8e47f195/idmtools_core/idmtools/analysis/analyze_manager.py#L273

**Comment by devclinton** [comment]
* How hard is this fix?

**Comment by jps1** [comment]
@shchen-idmod please confirm whether this is fixed.

**Comment by shchen-idmod** [comment]
This is no longer issue. Close it.
