### ISSUE TITLE
pygit2 dependency breaking install on my Ubuntu machine

### ISSUE THREAD

**Issue by jonathanhhb** [InstituteforDiseaseModeling/idmtools#1893]
**Table of Contents**

    - [Description](#description)
    - [What I Did](#what-i-did)
- [Extras](#extras)

### Description

pip3 install of idmtools on Ubuntu 22 (Jammy Jelly) results in error due to pygit2 dependency. Manual install of libgit2-dev is required. 

### What I Did

![Screenshot from 2022-10-06 10-10-05](https://user-images.githubusercontent.com/13157334/194377459-0dfe0bd0-f24d-4dfb-b3be-d7ac65e3ba0a.png)

# Extras

Is the git dependency still required?

**Comment by devclinton** [comment]
It currently is required. I think the latest pygit2 hasn't had universal wheels built. Unfortunately we use git within part of our utility classes to add tags easily

**Comment by YeChen-IDM** [comment]
We are seeing the same error when running emodpy-malaria tests in Jenkins with docker image: https://packages.idmod.org/ui/repos/tree/General/docker-production/idm/dtk-rpm-builder/0.1

**Comment by YeChen-IDM** [comment]
I am not able to workaround this issue in the [dtk-rpm-builder/0.1] image since the latest libgit2 library available for that OS is 0.26 which is not compatible with the latest pygit2.
pygit2-1.10.1 has no problem in the image, could we change dependency of pygit2 to version 1.10.1?

**Comment by shchen-idmod** [comment]
pygit2>=1.4.0,<=1.10.1

**Comment by devclinton** [comment]
Closing from #1960 
Also related, ticket #2126 for future work here

**Comment by shchen-idmod** [comment]
Reopen this issue. We can lift restriction for pygit2 <=1.10.1. current version is 1.13.3. Need to test on dtk-rpm-builder image and python 3.8 to 3.12

**Comment by ZDu-IDM** [comment]
Fixed.
