### ISSUE TITLE
idmtools-platform-local move to new repo

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/idmtools#1926]
Move local platform to new repo

* TODO Break down into smaller tasks

**Comment by devclinton** [comment]
* [ ] - Create New Repo
* [ ] - Move Code to New Repo
* [ ] - Rearrange code to build/test in new repo
* [ ] - Arrange test to call from core
* [ ] - Fix docs
* [ ] - Remove from core repo

**Comment by shchen-idmod** [comment]
The only task left is remove idmtools_platform_local from idmtools repo

**Comment by ZDu-IDM** [comment]
Completed in idmtools 1.7.10
