### ISSUE TITLE
Can not find Eradication when use shared folder 

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#1950]
NU uses shared folder at /projects/b1139/
And they put everything in this shared folder like sif files and emodpy-malaria repo
They also run slurm examples from emodpy-malaria within this folder instead of their home dir

Now they got error like this (I reproed)
FATAL:   stat /home/scj6369/Assets/Eradication: no such file or directory

**Comment by devclinton** [comment]
Are they using bridge mode? If so have you tried setting your bridge directory to use the shared disc?

**Comment by devclinton** [comment]
https://github.com/InstituteforDiseaseModeling/idmtools/blob/master/idmtools_slurm_utils/idmtools_slurm_utils/cli.py#L91 and

**Comment by shchen-idmod** [comment]
No, I can repro in both modes.(local and bridged)

**Comment by shchen-idmod** [comment]
> I can repro in both modes.(local and bridged)

**Comment by shchen-idmod** [comment]
So current workaround is to change SIF_PATH like this in user code ( ie. example_slurm.py or manifest.py)
`manifest.SIF_PATH = "--bind /projects /projects/b1139/dtk_run_rocky_py39.sif"`

**Comment by shchen-idmod** [comment]
This bug is still there for singularity use for shared project folder case. Above workaround works fine. But it is still a workaround which looks odd to put "--bind " in front of sif_path.

**Comment by devclinton** [comment]
@shchen-idmod - Did we ever document the workaround for this? I think if we do that, we can close this ticket for now and fix later if it is something that users have to deal with. Do we know how often users are encountering at NYU/NU?

**Comment by devclinton** [comment]
Fixed
