### ISSUE TITLE
slurm job count issue with add_multiple_parameter_sweep_definition

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#1963]
[emodpy_test.py.txt](https://github.com/InstituteforDiseaseModeling/idmtools/files/10136473/emodpy_test.py.txt)

This is the example Anne from NU is using.  she found issue with this example (I can repro myself)
The issue is script create right amount of simulation (45 total). 
but when do squeue, it shows total 720 jobs:
```
(emodpy_malaria_idmtools_pip_10_25) [scj6369@quser22 idmtools_core]$ squeue -u scj6369
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
8099350_[11-720%10     b1139 sbatch.s  scj6369 PD       0:00      1 (JobArrayTaskLimit)
         8099350_1     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_2     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_3     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_4     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_5     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_6     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_7     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_8     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
         8099350_9     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
        8099350_10     b1139 sbatch.s  scj6369  R       0:08      1 qnode0029
(emodpy_malaria_idmtools_pip_10_25) [scj6369@quser22 idmtools_core]$ scancel 8099350
```
720 = 45 * 16
Don't know where that 16 comes from. 
I have try to use max_workers=1, or max_threads=1, did not fix the issue.

Script will stop run after 45 simulation finished. but slurm job will continue running unless I do scancel.

Also script is running correctly in COMPS. and slurm. just squeue job have way more extra. This is only for doing sweeping with add_multiple_parameter_sweep_definition

**Comment by ZDu-IDM** [comment]
Done with idmtools release 1.7.3
