### ISSUE TITLE
Disable simluations in Experiment metadata for now 

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/idmtools#1977]
https://github.com/InstituteforDiseaseModeling/idmtools/blob/948b128dc03c6e7a479fadefc3f9ebf66203face/idmtools_core/idmtools/entities/experiment.py#L576

Remove from tests:
![image](https://user-images.githubusercontent.com/208629/206782992-6aa262ea-0047-449b-a7e0-07368acb75ce.png)

**Comment by ZDu-IDM** [comment]
Done with idmtools release 1.7.4
