### ISSUE TITLE
Potential issue with max count of simulations in slurm platform

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#1998]
See this error when simulation count is over 1000 in idm slurm cluster 10.24.15.109 
`sbatch: error: Batch job submission failed: Invalid job array specification`

Turns out we have maxarraysize config to 1000:
scontrol show config | grep -i array
MaxArraySize            = 1000
in QUEST:
scontrol show config | grep -i array
MaxArraySize            = 20000

So if someone from Quest run simulation over 20000, they could see this error and simulation won't run.

**Comment by devclinton** [comment]
* [] - Make the MaxArraySize Configurable
* [] - Make the Default for MaxArraySize the slurm default(maybe cli output?)
* [] - Handle situations where the job count is bigger than MaxArraySize(maybe split experiment up into multiple sbatch jobs).

**Comment by ZDu-IDM** [comment]
Update: we need to consider the following when working on this task (mentioned by Clinton)

- [ ]  - Make the MaxArraySize pull from config by default(if possible)
- [ ]  - Make the Default for MaxArraySize the slurm default(maybe cli output?)
- [ ]  - Handle situations where the job count is bigger than MaxArraySize(maybe split experiment up into multiple sbatch jobs).

Design: we have to break down the big slurm array job into some smaller slurm array jobs!

Implementation:  the following need to be implemented:

- Scripts/code need to be refactored to generate multiple Slurm jobs
•	Single/Multiple sbatch.sh files?
•	Python code or bash script approach?
- Retrieve MaxArraySize from Slurm configuration and take it into account when building Slurm job array
- Provide user option to set array size they like
- Store multiple Slurm job ids and display to user/screen
- Multiple Slurm jobs: dependency? Provide user with option
- Apply this consideration to cancel experiment case and verify working as before
- Verify idmtools-calibra still works (which uses cancel functionality)
- Consider the Bridged mode case in SlurmPlatform

**Comment by shchen-idmod** [comment]
Fixed in 1.7.7
