### ISSUE TITLE
slurm commission take too much memory which can exceeds head node's max memory 

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#2000]
**Table of Contents**

    - [Description](#description)
    - [What I Did](#what-i-did)
- [Extras](#extras)

### Description

Currently Annie from Northwestern U can not run serialized simulations (after burnin). It always "Killed" with 800 simulations.

### What I Did

I can repro her error in QUEST. when simulations > 400(maybe less) with her script, program got "Killed" from console without even start initialization yet(not hit "Initializing objects for creation ..." message from batch_create_items function. the error message sometime print error code 137

### Extras
Quest login node only have 4G memory. using memory profiler you can tell experiment.run(wait_until_done=True) can exceed 4G with over 400 simulations. 

This is print out when you login to Quest:
"You can use up to 4 cores and 4GB of memory on Quest's login nodes for all the commands and code you run there. We encourage you to submit jobs to Quest's compute nodes instead of running jobs on login nodes, as compute nodes provide access to significantly more resources. Please see https://services.northwestern.edu/TDClient/30/Portal/KB/ArticleDet?ID=1964. "

**Comment by shchen-idmod** [comment]
All scripts in Quest my dir: /home/sch6369/github/emodpy-malaria/examples/burnin_create_and_use_sweep_larval_habitat1/. Let me know if you need access.

**Comment by shchen-idmod** [comment]
memory almost hit 4G with only 450 sims:
![memory_old](https://user-images.githubusercontent.com/38014764/214907119-7973c0b6-46be-4233-a226-2896d3acdeb6.PNG)

**Comment by shchen-idmod** [comment]
Over all memory allocation with only 12 sims:
[memory.txt](https://github.com/InstituteforDiseaseModeling/idmtools/files/10511906/memory.txt)

**Comment by devclinton** [comment]
1. [ ] - Workaround documentation to the user is high priority - dry run + extra scripts.
2. [ ] - Same workaround in our official docs
3. [ ] - Solve long-term problem
