### ISSUE TITLE
iplatform non-descriptive error message: invalid type

### ISSUE THREAD

**Issue by ckirkman-IDM** [InstituteforDiseaseModeling/idmtools#2028]
The following eroor in iplatform.py is unhelpful without information regarding the actual type of object. Please update the message to provide more information, containing at least the object type. Took more time than it should have to figure out what the issue was because of this.

 File "/gpfs/home/kirkmc01/environments/hiv_workflow-p38/lib/python3.8/site-packages/idmtools/entities/iplatform.py", line 212, in get_item
    raise ValueError("The provided type is invalid or not supported by this platform...")

**Comment by devclinton** [comment]
Include the type in the error message
