### ISSUE TITLE
Add support for DockerLocalPlatform

### ISSUE THREAD

**Issue by jonathanhhb** [InstituteforDiseaseModeling/idmtools#2030]
Add support for a LocalPlatform that uses Docker to run Experiments on a user's local machine regardless of what the target env is for the model binary. 

Assume the user has docker installed already.
Assume the user has to provide a docker image.

**Comment by devclinton** [comment]
We already have this but it needs cleaned up and documented as part of the old local platform. We will be renaming that to container platform later and it should work on docker locally, or kubernetes.
