### ISSUE TITLE
Add support for ClientLocalPlatform

### ISSUE THREAD

**Issue by jonathanhhb** [InstituteforDiseaseModeling/idmtools#2031]
Add a version of LocalPlatform that does execution via webservice calls. This is not FilePlatform, LinuxLocalPlatform, or DockerLocalPlatform. Assets would be POST-ed to the webservice. Some minimal webservice API would be assumed.

**Comment by ZDu-IDM** [comment]
With the container platform, user will be able to run EMOD on local computer.

**Comment by jps1** [comment]
This is being done in ContainerPlatform.
