### ISSUE TITLE
Assetization workflow for generating SIF image should track using Asset ID instead of AC ID

### ISSUE THREAD

**Issue by jps1** [InstituteforDiseaseModeling/idmtools#2032]
Currently, when going through the assetization workflow for generating a SIF image, users are given back an AC ID representing an Asset Collection containing a single file (the SIF).  That AC is then combined with other dependencies when actually running the user's simulations.  However, the original AC is never actually used as-is (only the contained SIF).

In Staging, where we added functionality to identify unused assets/ACs for permanent deletion, this leads to deleting an AC that COMPS has no references to but that the user is tracking through its ID.  As a result, we have been reluctant to enable this functionality in production.  If functionality were added so users tracked these SIF files by the asset ID instead, that would allow us to turn this feature on (and save quite a bit of disk space).

**Comment by devclinton** [comment]
* We don't have api for asset id? How do we get that? 
* Scope work: if api exists, how hard is it? What changes

**Comment by devclinton** [comment]
Most likely emodpy will need an update @ https://github.com/InstituteforDiseaseModeling/emodpy/blob/d1c2ddea7762add9b19ef46a16d761231ae8697c/emodpy/emod_task.py#L511C16-L511C41****

**Comment by shchen-idmod** [comment]
Fixed in release 1.7.10
