### ISSUE TITLE
slurm platform is possibly dependent on singularity 3.10 and breaks with earlier versions

### ISSUE THREAD

**Issue by ckirkman-IDM** [InstituteforDiseaseModeling/idmtools#2034]
At NYU on their BigPurple cluster, they have singularity < 3.10 currently available. I checked with Zhaowei and Sharon and they indicated the slurm platform was developed with singularity 3.10 in mind. I cannot currently test 3.10 to verify its behavior, but I have tested 3.9, 3.1.

Not all versions of singularity map the FULL current working directory into the container automatically. Especially symlinks; they are not followed in full

e.g.
In a simulation directory, there is an Assets directory symlink:

"""
./Assets -> some_other_path/
"""
... where ...

"""
some_other_path/
use_this.sif
post_processor.py
...
"""

At the command line, NOT in the container, one can list "ls Assets/*" and it will list the files within some_other_path/ (following the symlink). I can verify that up through singularity 3.9, if one does the same "ls Assets" within the running container, one gets:
""""
File not found  
"""
One cannot even "cd" into Assets. The symlink "Assets" maps into the container as a file, not a directory with files in it.

I have yet to find a way to cause singularity to follow the symlinks when mapping the current working directory, though I have found a couple of potential workarounds.

1) Create an empty Assets directory in each simulation directory, then map the actual (current symlink destination) assets directory contents into this at run time via singularity arg: **-B ../Assets:$PWD/Assets** . This will map the files in the actual assets directory into the blank receiving directory ./Assets, as currently intended. This replaces having a symlink. We create an actual directory instead.

2) Map ../Assets (symlinked, actual assets dir) into another root path in the container, e.g. /Assets, and update "singularity exec" command to know about it. 
**-B ../Assets:/Assets**
This will mean a difference in behavior for specifying e.g. EMOD post processor files on COMPS vs slurm platform (COMPS style: ./Assets/dtk_post_process.py vs slurm platform style: /Assets/dtk_post_process.py). No pre-existing symlink or blank ./Assets directory needed

**Comment by ckirkman-IDM** [comment]
@devclinton @ZDu-IDM @shchen-idmod 
After further exploration, the issue seems to be that singularity does not guarantee (system dependent?) that sym links to directories/files outside the explicitly mounted directories will be available. e.g.
```
lrwxrwxrwx 1 kirkmc01 kirkmc01    111 Jun  6 14:39 Assets -> /gpfs/scratch/kirkmc01/testdir/395f12b4-1b97-4318-b2b2-417a389ba147/7cdbdc01-ea63-4bbc-9b27-d1b8c8b512f0/Assets
```
... may or may not resolve to the directories sym linked to when "singularity shell/exec" is invoked... UNLESS ... the link destination is explicitly mounted (because the destination of the sym link is outside of the working directory, not within it).

So a solution that appears to work for singularity **3.1, 3.7, and 3.9 (untested on 3.10)** is to explicitly specify **both** the *current working directory* AND the *Assets sym linked directory*

Like so (from within a simulation directory):
```
singularity shell -B $(pwd) -B $(pwd)/../Assets --pwd $(pwd) /gpfs/data/bershteynlab/EMOD/singularity_images/centos_dtk-build.sif
```

Result (inside the container):
```
Singularity> pwd
/gpfs/scratch/kirkmc01/testdir/395f12b4-1b97-4318-b2b2-417a389ba147/7cdbdc01-ea63-4bbc-9b27-d1b8c8b512f0/71670cd7-9798-4ec7-ae33-d9dc6b3b2904
Singularity> ls -l
total 321
lrwxrwxrwx 1 kirkmc01 kirkmc01    111 Jun  6 14:39 Assets -> /gpfs/scratch/kirkmc01/testdir/395f12b4-1b97-4318-b2b2-417a389ba147/7cdbdc01-ea63-4bbc-9b27-d1b8c8b512f0/Assets
-rw-rw---- 1 kirkmc01 kirkmc01  26922 Jun  6 14:39 campaign.json
-rw-rw---- 1 kirkmc01 kirkmc01   6335 Jun  6 14:39 config.json
-rw-rw---- 1 kirkmc01 kirkmc01   9036 Jun  6 14:39 metadata.json
-rwxrwxrwx 1 kirkmc01 kirkmc01    800 Jun  6 14:39 _run.sh
-rw-rw---- 1 kirkmc01 kirkmc01 111005 Jun  6 14:39 tmpug2v930u.json
Singularity> ls -l Assets
lrwxrwxrwx 1 kirkmc01 kirkmc01 111 Jun  6 14:39 Assets -> /gpfs/scratch/kirkmc01/testdir/395f12b4-1b97-4318-b2b2-417a389ba147/7cdbdc01-ea63-4bbc-9b27-d1b8c8b512f0/Assets
Singularity> ls -l Assets/
total 6529
-rw------- 1 kirkmc01 kirkmc01  146460 Jun  6 14:39 calibration_ingest_form--testing.xlsm
-rwxrwxrwx 1 kirkmc01 kirkmc01 6424528 Jun  6 14:39 Eradication
-rw-rw---- 1 kirkmc01 kirkmc01     772 Jun  6 14:39 post_channel_config.json
drwxrwx--- 2 kirkmc01 kirkmc01    4096 Jun  6 14:39 python
```

This use case of **-B path** uses the default binding destination, where **-B path**  means: **-B path:path**, so this way the full-path symlink to the Assets directory is an explicitly mapped-in path to the singularity container, hence the link works. I have also added explicit binding/mapping of the current working directory so that it can be set as the starting --pwd upon shell/exec invocation.

We will need to verify that this also works on singularity 3.10 (and 3.8, because it is on NU Quest cluster?), but the proposed change only updates how we call "singularity exec" and leaves intact the existing simulation directory structure, so it shouldn't be an invasive update at all! :)

**Comment by devclinton** [comment]
I think you resolved this @ckirkman-IDM now, so I am closing. We can reopen later
