### ISSUE TITLE
slurm platform may carry over erroneous SUCCESS cases from EMOD runs

### ISSUE THREAD

**Issue by ckirkman-IDM** [InstituteforDiseaseModeling/idmtools#2036]
The singularity exec scripts generated for submission to slurm run EMOD and the post processor as one line:
singularity exec Eradication -c config.json --python dtk_post_process ...

The issue here is that if Eradication runs successfully, it is currently not clear how slurm will handle the post processor. Will it report SUCCESS before the post processor runs completely (as with COMPS), giving a false SUCCESS report if the post processor fails? Will e.g. CalibManager try to download files for analysis from post processor output BEFORE the post processor finishes up?

Suggest:
Run any pre/in/post processor commands AFTER Eradication, but in the same script, something like:

singularity exec run_script.sh

```
run_script.sh:
!#/bin/bash
set -e


singularity exec Eradication -c config.json --python in_and_pre_processing_dir/
if post_process:
  ./Assets/post_process_file.py
```

This way, if any of the post processor fails, the simulation/task will be reported as FAILED, not SUCCESS. If a post processor is specified, **the user implicitly is asking that it be considered part of the model.**

**Comment by kfrey-idm** [comment]
May be more easily addressed as an EMOD issue?

Right now the python post-process is explicitly run after the return code is finalized (in the Eradication executable), so the 'success even if post-process fails' behavior is not something imposed by COMPS.

**Comment by ZDu-IDM** [comment]
This is handled in EMOD and has nothing to do with SlurmPlatform. Close the ticket.

**Comment by ckirkman-IDM** [comment]
Yes, this is an EMOD issue, but it is a design choice chosen by the EMOD development team. We have to live with  it because the fact that this issue still exists, years after it came to be, is that the EMOD team says, "EMOD completed successfully, it isn't our job to make sure the post processor succeeds" and the COMPS team says, "It isn't our job to make sure an executable run on our platform behaves normally (returns proper exit code)".

We must either:
1) live with this and ignore it. I find this unacceptable at this point.
2a) Fix it for the slurm platform so that (success == EMOD + post-processor complete without error)
2b) Actively push the COMPS development team to rectify the issue (success == EMOD + post-processor complete without error)
3) Actively push the EMOD team to force EMOD to NOT exit until the post-processor is complete (if running). Or remove post processing as an option and force all platforms to handle it as a separate step (I like this, but it requires more work probably).

It is my belief we must do 1, 2, or 3. 3 is IMO the best option, as it makes EMOD work normally on all platforms in one go. But I do not want to let this go yet again and end up with 1.

**Comment by kfrey-idm** [comment]
Setting the return code before post-processing was supposed to emphasize that the EMOD simulation was successful (output files generated completely). Those files could be re-analyzed by other scripts using server-side modeling tools without needing to re-run the (presumably expensive) sims.

I don't actually use that pattern. If my post-process fails, I'll delete the experiment and re-run it. My behavior may be a consequence of preferred sim complexity (I aim for high volume, low intensity). The SSMT scripts run out of a docker container on a single machine, and max out at 48 processes at the moment (Calculon uses 48 core machines), so re-analysis isn't all that efficient.

Changing the success/fail behavior in EMOD is straightforward. Set the return code after post-processing, not before.

**Comment by devclinton** [comment]
@ckirkman-IDM - Closing in lieu if [#4924](https://github.com/InstituteforDiseaseModeling/DtkTrunk/pull/4924)
