### ISSUE TITLE
Estimate of number of simulations being initialized is wrong when using ArmBuilder

### ISSUE THREAD

**Issue by pselvaraj87** [InstituteforDiseaseModeling/idmtools#2065]
### Description
Attached are screenshots of a 440 simulation experiment being initialized using ArmBuilder

Says 10240000 simulations are being initialized (I think this is from multiplying arms instead of adding them?) 

<img width="813" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/6496832/231598611-ee18c926-302f-493d-9e85-72a265d0502a.png">

And this is after initialization - showing the correct number of simulations:

<img width="741" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/6496832/231598700-535e1921-52ea-4be8-b859-3ce1f38cb55d.png">

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
