### ISSUE TITLE
Plan out maintenance release 3

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/idmtools#2131]
- [x] - Review and clean current issues in idmtools
- [x] - Ensure no outstanding issues are not documented
- [x] - Create initial priority list
- [x] - Schedule priority meeting(share list with team)
- [x] - Make final list of tasks for project
- [ ] - Present the Project Review

**Comment by ZDu-IDM** [comment]
Done or no not need, close it.
