### ISSUE TITLE
SLURM/FILE Platforms: idmtools_platform_pre/post_create_item are not invoked for AssetCollection

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2136]
For SLURM and FILE Platforms, the following Plugin Functions are not getting executed for AssetCollection:

	FunctionPluginManager.instance().hook.idmtools_platform_pre_create_item(item, kwargs=kwargs)
	FunctionPluginManager.instance().hook.idmtools_platform_post_create_item(item, kwargs=kwargs)

**Comment by shchen-idmod** [comment]
Fixed in #2149
