### ISSUE TITLE
Log typo when invoke hook

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2138]
File: idmtools\core\interfaces\iitem.py

    def post_creation(self, platform: 'IPlatform') -> None:
        """
        Called after the actual creation of the entity.

        Args:
            platform: Platform item was created on

        Returns:
            None
        """
        for hook in self.__post_creation_hooks:
            if logger.isEnabledFor(DEBUG):
                logger.debug(f'Calling pre-create hook named {hook.__name__ if hasattr(hook, "__name__") else str(hook)}')
            hook(self, platform)

[FIX]
Calling pre-create hook

--->

Calling post-create hook

**Comment by shchen-idmod** [comment]
Fixed in 1.7.9 release
