### ISSUE TITLE
Readable/meaningful suite/experiment/simulation output directory names

### ISSUE THREAD

**Issue by ckirkman-IDM** [InstituteforDiseaseModeling/idmtools#2143]
slurm platform:
---
Requested by NYU after demo of hiv_workflow, built up on idmtools.

Currently we get output directories for suite/experiment/simulations that look like:

```
<simulation dir>/SUITE_ID/EXPERIMENT_ID/SIMULATION_ID/<simulation_files>
```

However, this format is unreadable to a user and the ids mean nothing; so if a user wishes to find a suite/experiment/simulation with particular meanings, it is virtually impossible to do so.

I suggest changing the directory names to something like, e.g.:
```
<suite name>--SUITE_ID
```
or
```
<suite name>--TIMESTAMP
```

... or something more readable like this.

**Comment by devclinton** [comment]
There is an existing facility being worked on for this. There is an alternative id generator. Once that is working, it addresses this.
