### ISSUE TITLE
Format output json files in simulation directories

### ISSUE THREAD

**Issue by ckirkman-IDM** [InstituteforDiseaseModeling/idmtools#2144]
Slurm platform:
---
Requested by NYU after hiv_workflow demo

e.g. in:
```
<simulations dir>/SUITE_ID/EXPERIMENT_ID/SIMULATION_ID
```

If a user wishes to compare the e.g. campaign json files generated for two simulations, they are currently impossible to compare because the simulation json files are unformatted.

I propose adding indent=4 to the code currently writing out simulation json files so that we support visual/manual inspection.

**Comment by devclinton** [comment]
I think this is emodpy issue @ckirkman-IDM ?

**Comment by jps1** [comment]
This is not an idmtools issue, and is By Design.
