### ISSUE TITLE
Support for python 3.11 needs more recent pygit2

### ISSUE THREAD

**Issue by kfrey-idm** [InstituteforDiseaseModeling/idmtools#2152]
I can't `pip install` idmtools or any emodpy in python 3.11 on Windows because the required versions of pygit2 are not available.

When create a virtual environment with python 3.11 on windows and try to pip install idmtools, it will fail because there is no wheel file for the currently required version of pygit2, so pip will try to build the correct version of a wheel file, and fail because Windows doesn't have the correct compiler installed.

Please review if the requirement for `pygit2<=1.10.1` is still necessary:
https://github.com/InstituteforDiseaseModeling/idmtools/commit/12302e1ac744cfcfb48265edc494e85a0bfcb2d7

**Comment by shchen-idmod** [comment]
pygit2 depends on libgit2 which is added to windows wheel bundle for python 3.11 starting from pygit2 1.11.1
I will update requirements.txt by removing <1.10.1 restriction in next release

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release

**Comment by kfrey-idm** [comment]
Thank you @shchen-idmod!
