### ISSUE TITLE
ArmSimulationBuilder needs rasie exception for call to add_sweep_definition and add_multiple_parameter_sweep_definition

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2167]
Currently ArmSimulationBuilder doesn't support two methods
- add_sweep_definition 
- add_multiple_parameter_sweep_definition
however, user see these two options which may confuse users.

It is better to let user know by messge

       raise ValueError(f"Please use SweepArm instead, or use SimulationBuilder directly!")

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
