### ISSUE TITLE
Refactor ArmSimulationBuilder and move general functionality to a base class

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2168]
Current ArmSimulationBuilder inherits from SimulationBuilder, and they share some functionality but handle some cases differently. 

Suggest to refactor the  ArmSimulationBuilder (as well as SimulationBuilder) by moving some basic functionality to some base class.

For example,
- move basic functions from SimulationBuildder to SweepArm
- SimulationBuilder will inherits from SweepArm
- ArmSimulationBuilder will inherits from SimulationBuilder

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
