### ISSUE TITLE
For dry run, we better not to display 'check status message'

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2169]
Currently with dry run case, SlurmPlatform and Process platform display a message like the following

```
You may try the following command to check simulations running status: 
  idmtools slurm C:\Projects\idmtools_zhaowei\examples\native_slurm\SLURM_DATA status --exp-id 5c800dd9-b786-465e-830c-7874e9314fa7
```

Actually, for dry run case, no simulation got executed and therefore the displayed message has no meaning. We should disable the message.

**Comment by shchen-idmod** [comment]
Fixed in 1.7.11 release
