### ISSUE TITLE
Builder function add_multiple_parameter_sweep_definition doesn't support function with single dictionary parameter

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2192]

**Comment by ZDu-IDM** [comment]
Currently add_multiple_parameter_sweep_definition support function like:

def func(simulation, a: list, b:tuple):
    pass

it doesn't support the following case:

def func2(simulation, d: dict):
    pass

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
