### ISSUE TITLE
Combine two add sweeping functions into one

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2195]
idmtools SimulationBuilder support two methods:

- add_sweep_definition(function, ...)
- add_multiple_parameter_sweep_definition(function, ...)

The first method only supports one parameter sweeping. The second method support multiple parameters (>=2) sweeping.

Currently have to remember both two methods and choose the right one based on the need. This causes certain inconveniences to the users.

Investigation: it is better to combine the two methods into one.

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
