### ISSUE TITLE
Refactor Simulation Builders to remove duplicated code

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2196]
Currently the main objects SweepArm, SimulationBuilder and ArmSimulationBuilder have several parts of duplicated coding due to classes not properly inheriting structure. 

It is better to refactor the main classes and make proper class inheritance to reduce/remove the duplicated code.

**Comment by shchen-idmod** [comment]
Fixed in 1.7.10 release
