### ISSUE TITLE
Investigation: run each simulation on SLURM with multi cores

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2247]
For each simulation on SLURM, the command we run is _run.sh and it contains the actual command:

`singularity exec /home/zdf1921/shared/rocky_dtk_runner_py39.sif Assets/Eradication --config config.json --dll-path ./Assets --input-path ./Assets\;.`

It works fine in my testing example and generated the expected results in output folder (as seen on COMPS).

Based on NYU user's e-mail suggestion, I changed the command to the following (add 'mpirun -n 4'):

`singularity exec /home/zdf1921/shared/rocky_dtk_runner_py39.sif mpirun -n 4 Assets/Eradication --config config.json --dll-path ./Assets --input-path ./Assets\;.`

The file stdout.txt seems like it does use multi cores, however every simulation execution failed. 

Please refer to attached file stdout.txt for details.
[stdout.txt](https://github.com/InstituteforDiseaseModeling/idmtools/files/14924221/stdout.txt)

**Comment by kfrey-idm** [comment]
There can be odd issues when running a simulation where num_cores > num_nodes. It looks like there was probably an unhandled exception on the rank 3 process because it didn't have any nodes assigned:
```
00:00:01 [3] [I] [Simulation] Rank 3 contributes 0 nodes...
00:00:01 [3] [I] [Simulation] Rank map contents not displayed until NodeRankMap::ToString() (re)implemented.
00:00:01 [3] [W] [Simulation] Rank 3 wasn't assigned any nodes! (# of procs is too big for simulation?)
00:00:01 [3] [I] [Eradication] Controller execution failed, exiting.
```

For the Generic branch, I've changed the behavior so it's an explicit exception: 
https://github.com/InstituteforDiseaseModeling/DtkTrunk/issues/4997

Not sure what the intended behavior is for the Malaria branch, should check with @Bridenbecker.

**Comment by ZDu-IDM** [comment]
More testing on NU SLURM platform, the results are not satisfactory, and I will collect my test results and write a test report later.

**Comment by ZDu-IDM** [comment]
[EMOD MPI Test Report (short).pdf](https://github.com/InstituteforDiseaseModeling/idmtools/files/15138656/EMOD.MPI.Test.Report.short.pdf)
[emod_mpi_test.zip](https://github.com/InstituteforDiseaseModeling/idmtools/files/15138659/emod_mpi_test.zip)

**Comment by shchen-idmod** [comment]
You are do few ways to trigger mpi:
1. ntasks=x in Platform("Slurm_Local", ntasks=x,...) -- This is prefer way to utilize slurm manager's schedule MPI jobs
2. Platform("Slurm_Local", mpi_type=mpirun ...) -- Only use this if there is slurm does not support MPI jobs

Also you need to have multiple demographic nodes to run MPI
