### ISSUE TITLE
SlurmPlatform doc missing parameters information

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/idmtools#2303]
SlurmPlatform offers a range of parameters to assist users in running simulations efficiently. Currently, the documentation does not include a dedicated page detailing these parameters and their usage. Here are some key parameters:

'ntasks', 'partition', 'nodes', 'mail_type', 'mail_user', 'ntasks_per_core', 'cpus_per_task', 'mem_per_cpu', 'time', 'constraint', 'account', 'mem', 'exclusive', 'requeue', 'sbatch_custom', 'max_running_jobs', 'array_batch_size'

**Comment by shchen-idmod** [comment]
Fixed in 1.7.11 release
